export type Event = {
  title: string;
  date: string;
  venue: string;
  image: string;
  description: string;
  rating: number;
  rules: string[];
  capacity?: string;
  registrationFee: number;
  timeLimit?: string;
};

export const events: readonly Event[] = [
  {
    title: "Indian Group Dance",
    date: "",
    venue: "Main Stage",
    image: "",
    description: "A vibrant showcase of Indian dance styles and music.",
    rating: 5,
    registrationFee: 1500,
    rules: [
      "Only Indian styles and Indian music are allowed (Contemporary, Bollywood, Classical, Semi-Classical, Folk or any other Indian style).",
      "Any act of vulgarity in the costume or dance/indiscipline behaviour will lead to disqualification.",
      "Usage of props is allowed considering it is not harmful. (Usage of fire, water or any flammable objects will not be allowed.)",
      "Exceeding the time limit will lead to a reduction in the score",
    ],
    capacity: "8-14 members",
    timeLimit: "5+1 minutes",
  },
  {
    title: "Fashion Walk",
    date: "",
    venue: "Main Stage",
    image: "",
    description: "Showcase your style, creativity, and confidence on the runway.",
    rating: 5,
    registrationFee: 1500,
    rules: [
      "No of Participants: 8 to 10 members",
      "Judging will be based on clothes, creativity, choreography, styling and walk.",
      "No vulgarity.",
      "Dress Code: Inappropriate outfits are not allowed—college norms are to be followed (e.g., no crop tops, sleeveless tops, off-shoulder tops, deep neck tops, backless tops, sheer tops, ripped jeans).",
      "Stockings to be worn (no sheer stockings).",
      "Violation of dress code/any rules will lead to disqualification.",
    ],
    capacity: "8-10 members",
    timeLimit: "6+2 minutes",
  },
  {
    title: "Indian Group Singing",
    date: "",
    venue: "University Auditorium",
    image: "",
    description: "A melodious journey through Indian languages and genres.",
    rating: 5,
    registrationFee: 1000,
    rules: [
      "No of Participants: 3 to 8 members (including instrumentalists)",
      "Teams must strictly adhere to the time limit.",
      "All Indian languages and genres are allowed.",
      "Usage of karaoke is NOT allowed.",
      "Participants have to carry their own instruments (a drum kit will be provided).",
      "Any kind of vulgarity will lead to immediate disqualification.",
    ],
    capacity: "3-8 members",
    timeLimit: "5+2 minutes",
  },
  {
    title: "Western Group Singing",
    date: "",
    venue: "University Auditorium",
    image: "",
    description: "A celebration of vocal harmony and live Western music.",
    rating: 5,
    registrationFee: 1000,
    rules: [
      "No of Participants: 6 to 10 members",
      "Total Teams allowed: Max two per college, Cap at 15 teams",
      "Songs must be in English.",
      "Teams may use live instruments only (Acoustic, Keyboard, Basic Perc like Cajon, etc).",
      "Use of backing vocals in tracks is prohibited.",
      "Teams must bring their own instruments.",
      "Stage setup and soundcheck must be completed within the allotted time",
      "Exceeding the time limit may result in a penalty or disqualification.",
      "Use of vulgar language is prohibited.",
    ],
    capacity: "6-10 members, 2 team per college. Cap at 15 teams",
    timeLimit: "6+2 minutes (6 minutes performance + 2 minute soundcheck)",
  },
  {
    title: "Mad Ads",
    date: "",
    venue: "Main Stage",
    image: "",
    description: "Creative advertisements with humor and ingenuity.",
    rating: 5,
    registrationFee: 1000,
    rules: ["Number of rounds : 2"],
    capacity: "6-8 members",
    timeLimit: "3+1 minutes",
  },
  {
    title: "Personality",
    date: "",
    venue: "University Auditorium",
    image: "",
    description: "An individual event showcasing charisma and uniqueness.",
    rating: 5,
    registrationFee: 500,
    rules: [
      "No of Participants: Individual event",
      "Vulgarity, obscenity and offensive content are strictly prohibited.",
      "Props will be allowed at the Judge's discretion.",
      "There could be multiple rounds left to the Judges.",
    ],
    capacity: undefined,
  },
  {
    title: "Street Play",
    date: "",
    venue: "Hostel Block",
    image: "",
    description: "Expressive performances on open themes with live sound.",
    rating: 4,
    registrationFee: 500,
    rules: [
      "Number of participants: 12-15 members",
      "No government, religion, or political party is to be targeted directly.",
      "Use of props is allowed.",
      "Theme: Open",
      "Vulgarity in language, gestures, and costumes will not be entertained and can lead to disqualification.",
      "The sound and music should be live.",
      "Audio tracks, digital sound or electronic instruments will not be allowed.",
      "Original and fresh scripts will be entertained.",
    ],
    capacity: "12-15 members",
    timeLimit: "18+2 minutes",
  },
  {
    title: "Mock Rock",
    date: "",
    venue: "University Auditorium",
    image: "",
    description: "A hilarious performance combining music, memes, and creativity.",
    rating: 4,
    registrationFee: 500,
    rules: [
      "Participants form teams to convey a story with the help of music and MEME references, adding their own comedic twists, exaggerated acting, and ridiculous props.",
      "Any language can be used in audio.",
      "Any vulgarity, profanity, or offensive actions regarding caste, religion, politics, or discrimination will lead to disqualification.",
      "Choreography, composition, costume, and audience reaction will be considered as well.",
    ],
    capacity: "6-8 members",
    timeLimit: "4+2 minutes",
  },
  {
    title: "Air Crash",
    date: "",
    venue: "",
    image: "",
    description: "On-the-spot characters and creative scenarios to test your imagination.",
    rating: 4,
    registrationFee: 350,
    rules: [
      "No prior preparations are required, as characters will be assigned by the judges to participants on the spot.",
      "Each round will include multiple segments, which will be announced by the judges.",
      "Any display of vulgarity, foul language, or obscene, or offensive content will result in immediate disqualification.",
    ],
    capacity: undefined,
  },
  {
    title: "Indian Solo Dance",
    date: "",
    venue: "Aloysius Hall",
    image: "",
    description: "Show your skills in Indian dance styles and captivate the audience.",
    rating: 4,
    registrationFee: 350,
    rules: [
      "Only Indian styles and Indian music are allowed (Contemporary, Bollywood, Classical, Semi-Classical, Folk or any other Indian style).",
      "Two contingent participants per College /University are allowed.",
      "Any act of vulgarity in the costume or dance/indiscipline behaviour during the event will lead to disqualification.",
      "Usage of props is allowed, considering it is not harmful (Usage of fire, water, or any flammable object will not be allowed).",
      "Exceeding the time limit will lead to a reduction in score.",
    ],
    capacity: "individual",
    timeLimit: "3+1 minutes (Inclusive of entry, stage set up and exit)",
  },
  {
    title: "Reel Making",
    date: "",
    venue: "",
    image: "",
    description: "Create captivating reels to showcase your creativity and win hearts.",
    rating: 4,
    registrationFee: 350,
    rules: [
      "Max length 2 minutes.",
      "Exceeding the time limit would lead to disqualification.",
      "Use of vulgar language or profanity will lead to disqualification.",
      "Results will be graded based on the judge's decision under the amount of engagement (likes, shares, views).",
      "Each university/college can have up to 3 registrations.",
      "Each team must submit their original content.",
      "Teams must focus on the theme of Visages and promote it.",
    ],
    capacity: "Individual",
  },
    {
      title: "Stand-up Comedy",
      date: "",
      venue: "",
      image: "",
      description: "An opportunity to showcase your comedic talent in front of an audience.",
      rating: 3,
      registrationFee: 250,
      rules: [
        "Only original material is allowed.",
        "Participants are not allowed to use profanity or offensive content.",
        "Time limit must be strictly adhered to.",
        "Two Rounds, R1 - Scheduled performance, R2 - Surprise round.",
      ],
      capacity: "Individual",
      timeLimit: "3+1 minutes",
    },
    {
      title: "Treasure Hunt",
      date: "",
      venue: "Campus-wide",
      image: "",
      description: "Follow clues and solve riddles to find the hidden treasure.",
      rating: 3,
      registrationFee: 500,
      rules: [
        "Teams of 3 members.",
        "The clues will be scattered across the campus.",
        "Any act of cheating, misbehavior, discussion with other teams or outside individuals, or the use of gadgets (unless explicitly instructed) is strictly prohibited and will result in instant disqualification.",
        "The first team to find the treasure wins.",
      ],
      capacity: "3 members",
      timeLimit: undefined,
    },
    {
      title: "Rap and Beatbox",
      date: "",
      venue: "",
      image: "",
      description:
        "A high-energy event featuring rappers and beatboxers competing in dynamic tag teams.",
      rating: 3,
      registrationFee: 250,
      rules: [
        "No of Participants: 2 in a team.",
        "Rappers and beatboxers will compete in tag teams.",
        "Showcase round: 3+1 minutes.",
        "Further rounds, if any, will be announced at the event based on the judge’s decision.",
        "There is no language barrier for participants.",
        "Participants will be disqualified for vulgarity and discrimination against contestants on any grounds.",
        "Originality is encouraged.",
      ],
      capacity: "2 members per team",
      timeLimit: "3+1 minutes (Showcase round)",
    },
    {
      title: "BGMI",
      date: "",
      venue: "Online",
      image: "",
      description: "An exhilarating online gaming tournament for BGMI enthusiasts, testing teamwork and strategy.",
      rating: 0,
      registrationFee: 250,
      rules: [
        "No of Participants: 4+1 (Substitution - Optional).",
        "All participants must be from the same college.",
        "The event will be completely online.",
        "After the qualification rounds, the top 18 teams will be selected for the main finals.",
        "In case of a draw, the team with the most kills would be declared the winner.",
        "The official BGMI E-Sports point system will be followed.",
        "Emulators/iPad players are not allowed.",
        "No third-party applications, Hacks, or Cheats are allowed. Any team accused of using such programs, if failing to produce any proof (POV), will be disqualified.",
        "Team-ups are not allowed.",
        "In-game ID and player information must be submitted prior, and no changes will be accepted after the commencement of the tournament.",
      ],
      capacity: "4+1 members per team",
      timeLimit: "As per BGMI tournament guidelines",
    },
    {
      title: "Meme Making",
      date: "",
      venue: "",
      image: "",
      description: "A fun and creative event where participants design memes based on on-the-spot themes within a limited time frame.",
      rating: 3,
      registrationFee: 250,
      rules: [
        "No of Participants: Individual Event (1 registration per college).",
        "Total Entries Allowed: Max 1 participant per college; a maximum of 15 participants overall.",
        "Theme Announcement: Themes will be provided on the spot, and participants must create memes within the given time frame.",
        "Time Limit: Participants will have 15 minutes to create and submit their memes.",
        "Submission Guidelines: Memes must be submitted in image format (.jpg or .png).",
        "Content Restrictions: Memes must not contain any offensive, vulgar, dark humor, political, or inappropriate content. Adherence to university guidelines is mandatory.",
        "Judgment Criteria: Creativity, originality, humor, and relevance to the theme will be evaluated and scored by the judges.",
        "Malpractice: Any form of plagiarism, pre-prepared memes, or use of unauthorized gadgets will result in instant disqualification.",
      ],
      capacity: "15 participants overall (1 participant per college)",
      timeLimit: "15 minutes",
    },

    {
      title: "Battle of Bands",
      date: "",
      venue: "",
      image: "",
      description: "A thrilling musical competition where college bands battle it out with electrifying performances.",
      rating: 2000,
      registrationFee: 0,
      rules: [
        "Total entry: 15 (first come, first serve basis).",
        "It is not an open event. Entry is restricted to college students, including SJU.",
        "SJU Bands: Maximum of 3 bands only (first come, first serve basis).",
        "Number of members in a team: 4 to 8.",
        "Total time for performance: 8 minutes stage performance, 2 minutes setup.",
        "Only drum kits will be provided. Participants should bring other instruments.",
        "Both western and Indian songs can be performed.",
        "Participants can represent only one band. If seen in multiple bands, the team will be disqualified.",
        "No use of vulgar language; participants will be disqualified for violations.",
        "Original music is appreciated.",
        "Judges' decision will be final.",
      ],
      capacity: "15 bands (4-8 members per band)",
      timeLimit: "8 minutes stage performance + 2 minutes setup",
    },
    {
      title: "Improv",
      date: "",
      venue: "",
      image: "",
      description: "A dynamic and spontaneous event where teams create entertaining and unpredictable skits based on random prompts.",
      rating: 3,
      registrationFee: 250,
      rules: [
        "No of Participants: Two Members Per Team.",
        "Participants will receive random scenarios, characters, or themes with only a few moments to prepare, resulting in anything from hilarious skits to thought-provoking scenes.",
        "Whether you’re an experienced performer or trying improv for the first time, this event is all about fun, creativity, and spot brilliance.",
        "With audience participation adding an extra twist, every performance promises to be uniquely exciting and unpredictable!",
      ],
      capacity: "Two members per team",
      timeLimit: "As per event structure",
    },
    {
      title: "Face Painting",
      date: "",
      venue: "",
      image: "",
      description: "A creative event where participants showcase their artistic skills by painting faces inspired by cultural elements, traditions, or landmarks worldwide.",
      rating: 3,
      registrationFee: 250,
      rules: [
        "No of Participants: Individual event (The participant should bring along a model with them).",
        "Time Limit: 90 minutes for face painting and 30 minutes for presentation and judging (Total 2 hours).",
        "Participants must showcase their creativity by painting faces inspired by cultural elements, traditions, or landmarks worldwide.",
        "Themes can include iconic global symbols, national festivals, traditional attire, or significant cultural motifs.",
        "All materials must be brought by the participants.",
        "Non-compliance to the theme may result in disqualification.",
        "Only skin-safe, non-toxic paints should be used. Organisers are not responsible for any skin allergies or reactions.",
        "Face paintings will be judged based on their creativity, detailing, and relevance to the theme and presentation.",
      ],
      capacity: "Individual event (1 participant with a model)",
      timeLimit: "2 hours (90 minutes for painting + 30 minutes for judging)",
    },
    {
      title: "Murder Mystery",
      date: "",
      venue: "",
      image: "",
      description: "An engaging trio event where teams solve ciphers, compete in a treasure hunt, and use detective skills to unravel mysteries.",
      rating: 3,
      registrationFee: 250,
      rules: [
        "No of Participants: Trio Event (1 registration per college).",
        "Total Teams Allowed: Maximum 1 team per college, 10 teams in total.",
        "Teams will have to solve ciphers, compete in a treasure hunt, and use their detective skills to figure out clues and mysteries along the way.",
        "Teams will be eliminated round-wise.",
        "Malpractice or any use of gadgets unless instructed will lead to instant disqualification.",
      ],
      capacity: "3 members per team, 10 teams in total",
      timeLimit: "As per event structure",
    },
    {
      title: "Solo Instrumental",
      date: "",
      venue: "",
      image: "",
      description: "A platform for solo musicians to showcase their technical skills and creativity through live instrumental performances.",
      rating: 3,
      registrationFee: 250,
      rules: [
        "No of Participants: Individual event.",
        "Time Limit: 3+1 minutes.",
        "Participants must carry their instruments.",
        "A drum kit and keyboard will be provided.",
        "Backing tracks are not allowed.",
        "Loop pedals and effects are permitted if they are operated live by the participant.",
        "An original composition is welcomed.",
        "No profanities will be tolerated.",
        "Contestants will be evaluated on Technical Skill, Creativity and Originality, Stage Presence, Musicality, and Time Management.",
      ],
      capacity: "Individual event",
      timeLimit: "3+1 minutes",
    },
    {
      title: "DJ Wars",
      date: "",
      venue: "",
      image: "",
      description: "A thrilling competition where DJs showcase their original mixes and battle for the ultimate title.",
      rating: 4,
      registrationFee: 350,
      rules: [
        "Number of Participants: Individual Participation.",
        "Time Limit: 10+2 minutes.",
        "Original mixes only. No premixes allowed.",
        "No profanity in the samples.",
        "Standard CDJ 3000 and DJM 900 mixers will be provided.",
      ],
      capacity: "Individual participation",
      timeLimit: "10+2 minutes",
    },
    {
      title: "Solo Classical Singing",
      date: "",
      venue: "",
      image: "",
      description: "A classical music event where participants showcase their vocal skills in Hindustani or Carnatic music.",
      rating: 4,
      registrationFee: 350,
      rules: [
        "No of Participants: Individual Participation.",
        "Time Limit: 3+1 minutes.",
        "Both Hindustani and Carnatic music are allowed.",
        "The use of electronic tanpura and electronic tabla is permitted (use of mobile applications for the same is allowed).",
        "Following the time limit is mandatory.",
        "One accompanying classical instrumentalist is permitted (this will not be given any extra consideration or points).",
      ],
      capacity: "Individual participation",
      timeLimit: "3+1 minutes",
    },
    {
      title: "Western Solo Music",
      date: "",
      venue: "",
      image: "",
      description: "A solo singing competition where participants perform English songs, showcasing their vocal prowess.",
      rating: 4,
      registrationFee: 350,
      rules: [
        "No of Participants: Individual Participation.",
        "Time Limit: 3+1 minutes.",
        "The song must be performed in English.",
        "Instrumental accompaniment is permitted.",
        "Use of backing tracks is strictly prohibited.",
        "The use of vulgar or inappropriate language is not allowed.",
        "Contestants will be evaluated solely based on their vocal performance.",
      ],
      capacity: "Individual participation",
      timeLimit: "3+1 minutes",
    },
    {
      title: "Indian Solo Singing",
      date: "",
      venue: "",
      image: "",
      description: "A solo singing competition where participants perform Indian songs based on specific themes, showcasing their vocal talent and creativity.",
      rating: 4,
      registrationFee: 350,
      rules: [
        "No of Participants: Individual Participation.",
        "Time Limit: 3+1 minutes.",
        "Participants will have to sing a song based on one of the following themes: 'Nature', 'Adipoli', or 'Retro (1980s-90s)'.",
        "Themes will be allotted to participants, at random, 3 days prior to the event.",
        "Songs must belong to Indian languages (any) and genres only.",
        "Those performing their original compositions needn't follow the themes.",
        "One accompanying instrumentalist is allowed.",
        "Use of Karaoke is not permitted.",
        "Use of tanpura is allowed.",
        "Following the time limit is mandatory.",
        "Pro-tip: A unique choice of song based on the theme may earn you brownie points!",
      ],
      capacity: "Individual participation",
      timeLimit: "3+1 minutes",
    },
    {
      title: "Art",
      date: "",
      venue: "",
      image: "",
      description: "",
      rating: 3,
      rules: [],
      registrationFee: 0,
    },
    {
      title: "Minute to Win It",
      date: "",
      venue: "",
      image: "",
      description: "",
      rating: 3,
      rules: [],
      registrationFee: 250,
    },
    {
      title: "Photography",
      date: "",
      venue: "",
      image: "",
      description: "",
      rating: 3,
      rules: [],
      registrationFee: 250,
    },
    {
      title: "Western Solo Dance",
      date: "",
      venue: "",
      image: "",
      description: "",
      rating: 4,
      rules: [],
      registrationFee: 350,
    }
]