export type Event = {
  title: string;
  date: string;
  venue: string;
  image: string;
  description: string;
  rating: number;
  rules: string[];
  capacity?: string;
  registrationFee: number;
  timeLimit?: string;
};

export const events: readonly Event[] = [
  {
    title: "Indian Group Dance",
    date: "",
    venue: "Main Stage",
    image: "",
    description: "A vibrant showcase of Indian dance styles and music.",
    rating: 5,
    registrationFee: 1500,
    rules: [
      "Only Indian styles and Indian music are allowed (Contemporary, Bollywood, Classical, Semi-Classical, Folk or any other Indian style).",
      "Any act of vulgarity in the costume or dance/indiscipline behaviour will lead to disqualification.",
      "Usage of props is allowed considering it is not harmful. (Usage of fire, water or any flammable objects will not be allowed.)",
      "Exceeding the time limit will lead to a reduction in the score",
    ],
    capacity: "8-14 members",
    timeLimit: "5+1 minutes",
  },
  {
    title: "Fashion Walk",
    date: "",
    venue: "Main Stage",
    image: "",
    description: "Showcase your style, creativity, and confidence on the runway.",
    rating: 5,
    registrationFee: 0,
    rules: [
      "No of Participants: 8 to 10 members",
      "Judging will be based on clothes, creativity, choreography, styling and walk.",
      "No vulgarity.",
      "Dress Code: Inappropriate outfits are not allowed—college norms are to be followed (e.g., no crop tops, sleeveless tops, off-shoulder tops, deep neck tops, backless tops, sheer tops, ripped jeans).",
      "Stockings to be worn (no sheer stockings).",
      "Violation of dress code/any rules will lead to disqualification.",
    ],
    capacity: undefined,
    timeLimit: "6+2 minutes",
  },
  {
    title: "Indian Group Singing",
    date: "",
    venue: "University Auditorium",
    image: "",
    description: "A melodious journey through Indian languages and genres.",
    rating: 5,
    registrationFee: 0,
    rules: [
      "No of Participants: 3 to 8 members (including instrumentalists)",
      "Teams must strictly adhere to the time limit.",
      "All Indian languages and genres are allowed.",
      "Usage of karaoke is NOT allowed.",
      "Participants have to carry their own instruments (a drum kit will be provided).",
      "Any kind of vulgarity will lead to immediate disqualification.",
    ],
    capacity: undefined,
    timeLimit: "5+2 minutes",
  },
  {
    title: "Western Group Singing",
    date: "",
    venue: "University Auditorium",
    image: "",
    description: "A celebration of vocal harmony and live Western music.",
    rating: 5,
    registrationFee: 0,
    rules: [
      "No of Participants: 6 to 10 members",
      "Total Teams allowed: Max two per college, Cap at 15 teams",
      "Songs must be in English.",
      "Teams may use live instruments only (Acoustic, Keyboard, Basic Perc like Cajon, etc).",
      "Use of backing vocals in tracks is prohibited.",
      "Teams must bring their own instruments.",
      "Stage setup and soundcheck must be completed within the allotted time",
      "Exceeding the time limit may result in a penalty or disqualification.",
      "Use of vulgar language is prohibited.",
    ],
    capacity: "6-10 members, max 15 teams",
    timeLimit: "6+2 minutes (6 minutes performance + 2 minute soundcheck)",
  },
  {
    title: "Mad Ads",
    date: "",
    venue: "Main Stage",
    image: "",
    description: "Creative advertisements with humor and ingenuity.",
    rating: 5,
    registrationFee: 0,
    rules: [],
    capacity: "6-8 members",
    timeLimit: "3+1 minutes",
  },
  {
    title: "Personality",
    date: "",
    venue: "University Auditorium",
    image: "",
    description: "An individual event showcasing charisma and uniqueness.",
    rating: 5,
    registrationFee: 0,
    rules: [
      "No of Participants: Individual event",
      "Vulgarity, obscenity and offensive content are strictly prohibited.",
      "Props will be allowed at the Judge's discretion.",
      "There could be multiple rounds left to the Judges.",
    ],
    capacity: undefined,
  },
  {
    title: "Street Play",
    date: "",
    venue: "Hostel Block",
    image: "",
    description: "Expressive performances on open themes with live sound.",
    rating: 5,
    registrationFee: 500,
    rules: [
      "No government, religion, or political party is to be targeted directly.",
      "Use of props is allowed.",
      "Vulgarity in language, gestures, and costumes will not be entertained and can lead to disqualification.",
      "The sound and music should be live.",
      "Audio tracks, digital sound or electronic instruments will not be allowed.",
      "Original and fresh scripts will be entertained.",
    ],
    capacity: undefined,
    timeLimit: "18+2 minutes",
  },
  {
    title: "Mock Rock",
    date: "",
    venue: "University Auditorium",
    image: "",
    description: "A hilarious performance combining music, memes, and creativity.",
    rating: 5,
    registrationFee: 500,
    rules: [
      "Participants form teams to convey a story with the help of music and MEME references, adding their own comedic twists, exaggerated acting, and ridiculous props.",
      "Any language can be used in audio.",
      "Any vulgarity, profanity, or offensive actions regarding caste, religion, politics, or discrimination will lead to disqualification.",
      "Choreography, composition, costume, and audience reaction will be considered as well.",
    ],
    capacity: undefined,
    timeLimit: "4+2 minutes",
  },
  {
    title: "Air Crash",
    date: "",
    venue: "",
    image: "",
    description: "On-the-spot characters and creative scenarios to test your imagination.",
    rating: 5,
    registrationFee: 350,
    rules: [
      "No prior preparations are required, as characters will be assigned by the judges to participants on the spot.",
      "Each round will include multiple segments, which will be announced by the judges.",
      "Any display of vulgarity, foul language, or obscene, or offensive content will result in immediate disqualification.",
    ],
    capacity: undefined,
  },
  {
    title: "Indian Solo Dance",
    date: "",
    venue: "Aloysius Hall",
    image: "",
    description: "Show your skills in Indian dance styles and captivate the audience.",
    rating: 5,
    registrationFee: 350,
    rules: [
      "Only Indian styles and Indian music are allowed (Contemporary, Bollywood, Classical, Semi-Classical, Folk or any other Indian style).",
      "Two contingent participants per College /University are allowed.",
      "Any act of vulgarity in the costume or dance/indiscipline behaviour during the event will lead to disqualification.",
      "Usage of props is allowed, considering it is not harmful (Usage of fire, water, or any flammable object will not be allowed).",
      "Exceeding the time limit will lead to a reduction in score.",
    ],
    capacity: undefined,
    timeLimit: "3+1 minutes (Inclusive of entry, stage set up and exit)",
  },
  {
    title: "Reel Making",
    date: "",
    venue: "",
    image: "",
    description: "Create captivating reels to showcase your creativity and win hearts.",
    rating: 5,
    registrationFee: 350,
    rules: [
      "Max length 2 minutes.",
      "Exceeding the time limit would lead to disqualification.",
      "Use of vulgar language or profanity will lead to disqualification.",
      "Results will be graded based on the judge's decision under the amount of engagement (likes, shares, views).",
      "Each university/college can have up to 3 registrations.",
      "Each team must submit their original content.",
      "Teams must focus on the theme of Visages and promote it.",
    ],
    capacity: undefined,
  },
    {
      title: "Dance Battle",
      date: "",
      venue: "Main Stage",
      image: "",
      description: "A high-energy dance-off to showcase street dance skills.",
      rating: 5,
      registrationFee: 300,
      rules: [
        "Two participants per team.",
        "Dance styles: Hip-hop, Breakdance, Popping, Locking, or any street style.",
        "Vulgarity or offensive moves will lead to disqualification.",
        "Maximum 3 rounds per battle.",
      ],
      capacity: "2 members",
      timeLimit: "2 minutes",
    },
    {
      title: "Coding Challenge",
      date: "",
      venue: "Computer Lab",
      image: "",
      description: "Test your coding skills in a competitive environment.",
      rating: 5,
      registrationFee: 200,
      rules: [
        "Participants must complete the coding task within the given time limit.",
        "No external help or online search is allowed.",
        "The task will be in C++, Python, or JavaScript.",
        "Time extensions will not be given.",
      ],
      capacity: "Individual",
      timeLimit: "1 hour",
    },
    {
      title: "Photography Contest",
      date: "",
      venue: "Campus Grounds",
      image: "",
      description: "Showcase your photography skills with a creative shot.",
      rating: 5,
      registrationFee: 100,
      rules: [
        "Only original photos are allowed.",
        "Photo editing is allowed but not to the point of distorting the image.",
        "Entries must be submitted in JPG or PNG format.",
        "Participants must follow the theme given on the spot.",
      ],
      capacity: "Individual",
      timeLimit: "N/A",
    },
    {
      title: "Sketching",
      date: "",
      venue: "Art Room",
      image: "",
      description: "Bring your imagination to life with a pencil and paper.",
      rating: 5,
      registrationFee: 100,
      rules: [
        "Participants must use pencil, charcoal, or ink (No color pencils or crayons).",
        "The theme will be given at the start of the event.",
        "No digital tools allowed.",
        "Maximum size of the sketch: A3 paper.",
      ],
      capacity: "Individual",
      timeLimit: "1 hour",
    },
    {
      title: "Quiz Competition",
      date: "",
      venue: "Auditorium",
      image: "",
      description: "A test of knowledge across various fields.",
      rating: 5,
      registrationFee: 0,
      rules: [
        "Teams of 2-4 members.",
        "No mobile phones allowed during the quiz.",
        "All answers must be final upon submission.",
        "The quiz will have multiple rounds including general knowledge, technical, and current events.",
      ],
      capacity: "2-4 members",
      timeLimit: "1 hour",
    },
    {
      title: "Stand-up Comedy",
      date: "",
      venue: "Open Stage",
      image: "",
      description: "An opportunity to showcase your comedic talent in front of an audience.",
      rating: 5,
      registrationFee: 0,
      rules: [
        "Only original material is allowed.",
        "Participants are not allowed to use profanity or offensive content.",
        "Time limit must be strictly adhered to.",
        "Props may be used at the participant's discretion but must be non-disruptive.",
      ],
      capacity: "Individual",
      timeLimit: "5 minutes",
    },
    {
      title: "Short Film Making",
      date: "",
      venue: "Film Studio",
      image: "",
      description: "Create an impactful story in the form of a short film.",
      rating: 5,
      registrationFee: 300,
      rules: [
        "The film must be between 3 to 5 minutes long.",
        "No vulgar or offensive content.",
        "Films must be submitted in MP4 format.",
        "Original content only.",
      ],
      capacity: "Individual or Team (Max 5 members)",
      timeLimit: "3-5 minutes",
    },
    {
      title: "Rube Goldberg Machine",
      date: "",
      venue: "Workshop Area",
      image: "",
      description: "Create a complex machine to complete a simple task in an amusing way.",
      rating: 5,
      registrationFee: 250,
      rules: [
        "The machine must use a series of mechanical devices to complete a simple task.",
        "Participants must use everyday objects (no pre-built machines).",
        "The machine must run within a 3-minute time frame.",
        "No use of fire, liquids, or dangerous components.",
      ],
      capacity: "2-4 members",
      timeLimit: "3 minutes",
    },
    {
      title: "Gaming Tournament",
      date: "",
      venue: "Gaming Arena",
      image: "",
      description: "Compete against others in an intense video game tournament.",
      rating: 5,
      registrationFee: 200,
      rules: [
        "The tournament will have multiple stages.",
        "Only approved games will be used.",
        "Cheating or use of hacks will lead to immediate disqualification.",
        "Participants must bring their own controllers (if applicable).",
      ],
      capacity: "Individual or Team (Max 4 members)",
      timeLimit: "Varies by game",
    },
    {
      title: "Treasure Hunt",
      date: "",
      venue: "Campus-wide",
      image: "",
      description: "Follow clues and solve riddles to find the hidden treasure.",
      rating: 5,
      registrationFee: 100,
      rules: [
        "Teams of 2-4 members.",
        "The clues will be scattered across the campus.",
        "No mobile phones or GPS allowed.",
        "The first team to find the treasure wins.",
      ],
      capacity: "2-4 members",
      timeLimit: "1 hour",
    },
      {
        title: "Cooking Competition",
        date: "",
        venue: "Culinary Lab",
        image: "",
        description: "Show your culinary skills and creativity in the kitchen.",
        rating: 5,
        registrationFee: 200,
        rules: [
          "Participants must prepare a dish within the given time frame.",
          "All ingredients must be brought by the participants.",
          "The dish must be served within the allotted time.",
          "No pre-cooked ingredients or ready-made mixes allowed.",
        ],
        capacity: "Individual or Team (Max 2 members)",
        timeLimit: "1 hour",
      },
      {
        title: "Robotics Challenge",
        date: "",
        venue: "Tech Lab",
        image: "",
        description: "Build a robot to complete specific tasks in a competitive environment.",
        rating: 5,
        registrationFee: 500,
        rules: [
          "Teams of 2-4 members.",
          "Robots must be built using the provided kits or available materials.",
          "Robots should be autonomous (no manual control during the event).",
          "The robot must be able to complete the assigned task within the time frame.",
        ],
        capacity: "2-4 members",
        timeLimit: "Varies by task",
      },
      {
        title: "Poetry Slam",
        date: "",
        venue: "Open Stage",
        image: "",
        description: "An event to showcase your poetic expression and creativity.",
        rating: 5,
        registrationFee: 0,
        rules: [
          "Poems must be original and recited without music or props.",
          "Poems can be in any language.",
          "Content should not be offensive or vulgar.",
          "Time limit must be adhered to strictly.",
        ],
        capacity: "Individual",
        timeLimit: "3 minutes",
      },
      {
        title: "Beatboxing",
        date: "",
        venue: "Main Stage",
        image: "",
        description: "Compete in a beatboxing battle to showcase your vocal rhythm skills.",
        rating: 5,
        registrationFee: 0,
        rules: [
          "Participants must perform an original beatboxing routine.",
          "No pre-recorded sounds or external devices allowed.",
          "Participants should focus on creativity and rhythm.",
          "Vulgar language or offensive content will lead to disqualification.",
        ],
        capacity: "Individual",
        timeLimit: "3 minutes",
      },
      {
        title: "Chess Tournament",
        date: "",
        venue: "Game Room",
        image: "",
        description: "Compete in a high-stakes chess tournament to claim victory.",
        rating: 5,
        registrationFee: 100,
        rules: [
          "Each match will be played in a knockout format.",
          "Chess clocks will be used for time management.",
          "Participants must bring their own chess sets.",
          "No outside assistance during the game.",
        ],
        capacity: "Individual",
        timeLimit: "Varies (based on rounds)",
      },
      {
        title: "Spelling Bee",
        date: "",
        venue: "Auditorium",
        image: "",
        description: "Test your vocabulary and spelling skills in this challenging competition.",
        rating: 5,
        registrationFee: 0,
        rules: [
          "Participants must spell words correctly without any help.",
          "The words will be selected from various categories.",
          "No external aids, like phones or dictionaries, are allowed.",
          "The event is knockout-style, with each round eliminating the lowest scorer.",
        ],
        capacity: "Individual",
        timeLimit: "N/A",
      },
      {
        title: "Mime Act",
        date: "",
        venue: "Main Stage",
        image: "",
        description: "Use your body language to tell a story without words in this performance.",
        rating: 5,
        registrationFee: 0,
        rules: [
          "No talking or verbal expressions allowed during the performance.",
          "Props may be used but should not interfere with the act.",
          "Performance should be an original concept.",
          "Vulgarity or offensive actions will lead to disqualification.",
        ],
        capacity: "Individual or Team (Max 2 members)",
        timeLimit: "3 minutes",
      },
      {
        title: "Stand-up Comedy",
        date: "",
        venue: "Main Auditorium",
        image: "",
        description: "A humorous event to showcase your comic timing and creativity.",
        rating: 5,
        registrationFee: 0,
        rules: [
          "Participants must perform original comedy routines.",
          "Offensive language or vulgar content is strictly prohibited.",
          "Props may be used but should not distract from the performance.",
          "Judging will focus on creativity, humor, and timing.",
        ],
        capacity: "Individual",
        timeLimit: "5 minutes",
      },
      {
        title: "Poetry Recitation",
        date: "",
        venue: "Library Hall",
        image: "",
        description: "Recite poems from memory and express emotions with words.",
        rating: 5,
        registrationFee: 0,
        rules: [
          "Poems can be in any language.",
          "The participant must memorize and recite the poem without reading.",
          "Vulgar or offensive language is strictly prohibited.",
          "The participant can choose any poem, provided it's not longer than the time limit.",
        ],
        capacity: "Individual",
        timeLimit: "4 minutes",
      },
      {
        title: "Debate Competition",
        date: "",
        venue: "Debate Hall",
        image: "",
        description: "Engage in an intellectual debate on current topics.",
        rating: 5,
        registrationFee: 0,
        rules: [
          "Teams of 2 members.",
          "Each participant gets a 2-minute speaking time.",
          "Participants must stick to the topic and argue with logic and facts.",
          "No personal attacks or offensive language allowed.",
        ],
        capacity: "2 members",
        timeLimit: "Varies",
      },
      {
          title: "Pictionary",
          date: "",
          venue: "Activity Hall",
          image: "",
          description: "Draw your way to victory by guessing the words.",
          rating: 5,
          registrationFee: 0,
          rules: [
            "Teams of 3-5 members.",
            "Each team must take turns drawing the assigned word or phrase.",
            "No letters or numbers can be used while drawing.",
            "The timer will be set for each round, and the team must guess before time runs out.",
          ],
          capacity: "3-5 members",
          timeLimit: "2 minutes per round",
        },
        {
          title: "Treasure Hunt",
          date: "",
          venue: "Various Locations",
          image: "",
          description: "Follow clues and solve puzzles to find hidden treasures.",
          rating: 5,
          registrationFee: 100,
          rules: [
            "Teams of 2-4 members.",
            "The team that finds the treasure first wins.",
            "Participants must solve riddles and clues provided at each checkpoint.",
            "No external aids or tools allowed.",
          ],
          capacity: "2-4 members",
          timeLimit: "Varies by stage",
        },
        {
          title: "Quiz Competition",
          date: "",
          venue: "Auditorium",
          image: "",
          description: "Test your knowledge across various subjects in this competitive quiz.",
          rating: 5,
          registrationFee: 0,
          rules: [
            "Teams of 2-3 members.",
            "Questions will cover topics from general knowledge, science, history, and current events.",
            "No phones or external sources of information allowed.",
            "The quiz will be conducted in multiple rounds.",
          ],
          capacity: "2-3 members",
          timeLimit: "Varies by round",
        },
        {
          title: "Street Photography",
          date: "",
          venue: "City Streets",
          image: "",
          description: "Capture the essence of the city through the lens of a camera.",
          rating: 5,
          registrationFee: 0,
          rules: [
            "Participants must capture street scenes without disrupting normal life.",
            "Only natural lighting is allowed.",
            "Participants should submit their best 3 photos for judging.",
            "No excessive editing or manipulation of photos.",
          ],
          capacity: "Individual",
          timeLimit: "Submit photos within 2 hours",
        },
        {
          title: "Slam Poetry",
          date: "",
          venue: "Open Stage",
          image: "",
          description: "A performance art of spoken word poetry that is raw and powerful.",
          rating: 5,
          registrationFee: 0,
          rules: [
            "Poetry must be original.",
            "No props or music are allowed.",
            "Time limit must be adhered to strictly.",
            "Offensive or vulgar content will lead to disqualification.",
          ],
          capacity: "Individual",
          timeLimit: "3 minutes",
        },
        {
          title: "Dance Battle",
          date: "",
          venue: "Main Stage",
          image: "",
          description: "A battle of dance styles and creativity on the dance floor.",
          rating: 5,
          registrationFee: 0,
          rules: [
            "Participants must bring their own music.",
            "No vulgar or inappropriate dance moves.",
            "The battle will take place in a knockout format.",
            "The dance styles can vary, but each participant must perform a unique routine.",
          ],
          capacity: "Individual",
          timeLimit: "2 minutes per round",
        },
        {
          title: "Speed Reading",
          date: "",
          venue: "Reading Room",
          image: "",
          description: "Test your reading speed and comprehension in this competitive event.",
          rating: 5,
          registrationFee: 0,
          rules: [
            "Participants will be given a passage to read within a set time.",
            "Reading speed and comprehension will be tested.",
            "The participant must answer a set of questions related to the passage.",
            "No external assistance allowed.",
          ],
          capacity: "Individual",
          timeLimit: "Varies based on passage length",
        },
        {
          title: "Tug of War",
          date: "",
          venue: "Sports Ground",
          image: "",
          description: "A test of strength and teamwork in this classic team event.",
          rating: 5,
          registrationFee: 0,
          rules: [
            "Teams of 8-10 members.",
            "The rope must not touch the ground at any point during the match.",
            "Teams must work together to pull the rope across the designated line.",
            "No equipment, footwear, or attire that could cause injury is allowed.",
          ],
          capacity: "8-10 members",
          timeLimit: "N/A",
        },
        {
          title: "Paper Plane Challenge",
          date: "",
          venue: "Indoor Arena",
          image: "",
          description: "Craft the perfect paper plane and see how far it flies.",
          rating: 5,
          registrationFee: 0,
          rules: [
            "Participants must craft their own paper plane from a single sheet of paper.",
            "The plane must be thrown by hand without any additional materials or tools.",
            "The plane that flies the farthest wins.",
            "Only one attempt per participant.",
          ],
          capacity: "Individual",
          timeLimit: "1 minute per attempt",
        },
        {
          title: "Candle Making",
          date: "",
          venue: "Crafting Room",
          image: "",
          description: "Create your own custom candles in this hands-on workshop.",
          rating: 5,
          registrationFee: 200,
          rules: [
            "Participants must create a candle using the materials provided.",
            "Candles must be handmade and should include creative designs.",
            "All candles must be completed within the allotted time.",
            "Participants must adhere to safety rules while handling hot wax.",
          ],
          capacity: "Individual",
          timeLimit: "2 hours",
        },
];
